/**
 * Residential Electrification Model API
 * An API for REM, the Residential Electrification Model.
 *
 * The version of the OpenAPI document: 0.4.1
 * Contact: datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ImpactMetric } from './impactMetric';

/**
* A class to represent savings data for a particular fuel.
*/
export class FuelSavings {
    /**
    * The data if no upgrade is passed into the surrogate model.
    */
    'baseline': ImpactMetric;
    'upgrade'?: ImpactMetric | null;
    'delta'?: ImpactMetric | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "baseline",
            "baseName": "baseline",
            "type": "ImpactMetric"
        },
        {
            "name": "upgrade",
            "baseName": "upgrade",
            "type": "ImpactMetric"
        },
        {
            "name": "delta",
            "baseName": "delta",
            "type": "ImpactMetric"
        }    ];

    static getAttributeTypeMap() {
        return FuelSavings.attributeTypeMap;
    }
}

