/**
 * Residential Electrification Model API
 * An API for REM, the Residential Electrification Model.
 *
 * The version of the OpenAPI document: 0.4.2
 * Contact: datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricStatistics } from './metricStatistics';

/**
* Represents a collection of impacts associated with a fuel.
*/
export class ImpactMetric {
    /**
    * The energy consumed for the given fuel.
    */
    'energy': MetricStatistics;
    /**
    * The emissions produced by the given fuel.
    */
    'emissions': MetricStatistics;
    /**
    * The cost of consumed the given fuel.
    */
    'cost': MetricStatistics;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "energy",
            "baseName": "energy",
            "type": "MetricStatistics"
        },
        {
            "name": "emissions",
            "baseName": "emissions",
            "type": "MetricStatistics"
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "MetricStatistics"
        }    ];

    static getAttributeTypeMap() {
        return ImpactMetric.attributeTypeMap;
    }
}

