/**
 * Residential Electrification Model API
 * An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Quantity } from './quantity';

/**
* Represents a statistic associated with a particular fuel and type of impact.  Attributes ----------     mean: Mean.     median: Median.     percentile_20: 20th percentile.     percentile_80: 80th percentile.
*/
export class MetricStatistics {
    'mean': Quantity;
    'median': Quantity;
    'percentile20': Quantity;
    'percentile80': Quantity;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mean",
            "baseName": "mean",
            "type": "Quantity"
        },
        {
            "name": "median",
            "baseName": "median",
            "type": "Quantity"
        },
        {
            "name": "percentile20",
            "baseName": "percentile_20",
            "type": "Quantity"
        },
        {
            "name": "percentile80",
            "baseName": "percentile_80",
            "type": "Quantity"
        }    ];

    static getAttributeTypeMap() {
        return MetricStatistics.attributeTypeMap;
    }
}

