/**
 * Residential Electrification Model API An API for REM, the Residential
 * Electrification Model.
 *
 * The version of the OpenAPI document: 0.4.2 Contact:
 * datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/** A class to represent a quantity, which is a value with a unit. */
export class Quantity {
  /** The numerical value. */
  "value"?: number = 0.0;
  /** The unit. */
  "unit": string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "value",
      baseName: "value",
      type: "number",
    },
    {
      name: "unit",
      baseName: "unit",
      type: "string",
    },
  ];

  static getAttributeTypeMap() {
    return Quantity.attributeTypeMap;
  }
}
