/**
 * Residential Electrification Model API
 * An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* A class to represent a quantity, which is a value with units.  Attributes ----------     value (float): The numerical value.     units (str): The units.
*/
export class Quantity {
    'value'?: number = 0.0;
    'units': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Quantity.attributeTypeMap;
    }
}

