/**
 * Residential Electrification Model API
 * An API for REM, the Residential Electrification Model.
 *
 * The version of the OpenAPI document: 0.4.1
 * Contact: datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Any heating fuel, plus \\\"total\\\".
*/
export enum ResultFuelType {
    Electricity = <any> 'electricity',
    FuelOil = <any> 'fuel_oil',
    NaturalGas = <any> 'natural_gas',
    Propane = <any> 'propane',
    Total = <any> 'total'
}
