/**
 * Residential Electrification Model API
 * An API for REM, the Residential Electrification Model.         The other Rewiring America APIs and methodology for REM are [here](https://api.rewiringamerica.org/).
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: datascience@rewiringamerica.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Upgrades accepted by the REM API.
*/
export enum SupportedUpgrade {
    BasicEnclosure = <any> 'basic_enclosure',
    MinEffHpElecBackup = <any> 'min_eff_hp_elec_backup',
    HighEffHpElecBackup = <any> 'high_eff_hp_elec_backup',
    WholeHomeElectricMaxEffBasicEnclosure = <any> 'whole_home_electric_max_eff_basic_enclosure',
    MedEffHpHersSizingNoSetback = <any> 'med_eff_hp_hers_sizing_no_setback',
    MedEffHpHersSizingNoSetbackBasicEnclosure = <any> 'med_eff_hp_hers_sizing_no_setback_basic_enclosure'
}
